// leave off @2x/@3x
const Images = {
  logo: require('../Images/logo.png'),
  // clearLogo: require('../Images/top_logo.png'),
  // launch: require('../Images/launch-icon.png'),
  // ready: require('../Images/your-app.png'),
  // ignite: require('../Images/ignite_logo.png'),
  // igniteClear: require('../Images/ignite-logo-transparent.png'),
  // tileBg: require('../Images/tile_bg.png'),
  deal: require('../Images/megaphone.svg'),
  services: require('../Images/link.svg'),
  other: require('../Images/list.svg'),
  family: require('../Images/family.jpg'),
  kitchen: require('../Images/kitchen.jpeg'),
  food: require('../Images/food.jpg'),
  wash: require('../Images/wash.jpeg'),
  code: require('../Images/money-bag.svg'),
  slide1: require('../Images/slide1.jpg'),
  slide2: require('../Images/slide2.png'),
  slide3: require('../Images/slide3.jpg'),
  langBg: require('../Images/Image_9.png'),
  splash0: require('../Images/Bg.png'),
  splash1: require('../Images/splash_1.png'),
  splash2: require('../Images/splash_2.png'),
  splash3: require('../Images/splash_3.png'),
  mainLogin: require('../Images/mainLogin.png'),
  notificaion: require('../Images/notificaion_logo.png'),
  blueLogo: require('../Images/blue_logo_copy_2.png'),
  call: require('../Images/call_logo.png'),
  loginBackGround: require('../Images/shutterstock_5198937dd10.png'),
  chevronLeft: require('../Images/arrow_copy.png'),
  mapPin: require('../Images/pin_map.png'),
  home: require('../Images/home.png'),
  cart: require('../Images/cart.png'),
  filtter: require('../Images/filtter.png'),
  centerMenu: require('../Images/center_menu.png'),
  conversation: require('../Images/conversation.png'),
  profileIcon: require('../Images/Profile_icon.png'),
  passwordEye: require('../Images/passored_eye.png'),
  pickIcon: require('../Images/pick_copy.png'),
  Bitmap: require('../Images/Bitmap.png'),
  like: require('../Images/like_icon.png'),
  forgotPasswordBackground: require('../Images/shutterstock_519893710.png'),
  notificationIcon: require('../Images/notification_icon_copy.png'),
  searchIcon: require('../Images/search_copy.png'),
  language: require('../Images/languge_icon.png'),
  callIcon: require('../Images/call_icon.png'),
  wishActive: require('../Images/wishlist_icon_active.png'),
  wishUnactive: require('../Images/unwish.png'),
  likeBlue: require('../Images/like_icon.png'),
  likeWhite: require('../Images/like_white.png'),
  likeBlue1: require('../Images/like_blue.png'),
  likeWhite1: require('../Images/unlike.png'),
  share: require('../Images/share_icon.png'),
  addPhoto: require('../Images/add_photo.png'),
  toggleButtonbg: require('../Images/on_bg.png'),
  toggleButtonDot: require('../Images/on_cir.png'),
  listFeatureIcon: require('../Images/list.png'),
  x: require('../Images/x.png'),
  threeDots: require('../Images/Group.png'),
  setting: require('../Images/Settings_icon.png'),
  bgProfile: require('../Images/Profile_BG.png'),
  chevronRight: require('../Images/arrow.png'),
  arrowRight: require('../Images/arrow.png'),
  toggleButtonbgUnactive: require('../Images/off_bg.png'),
  addPostBg: require('../Images/add_post_bg.png'),
  camara: require('../Images/camara.png'),
  gallary: require('../Images/gallary.png'),
  xWhite: require('../Images/x_copy.png'),
  Terms: require('../Images/Terms.png'),
  Privacy: require('../Images/Privacy_Policy.png'),
  Help: require('../Images/Help.png'),
  xGray: require('../Images/Group_2.png'),
  sold: require('../Images/riboonsold.png'),
  featured: require('../Images/rep.png'),
  done: require('../Images/done.png'),
  chevronRightWhite: require('../Images/arrowWhite.png'),
  prime: require('../Images/PREMIUM_icon.png'),
  bgSeller: require('../Images/seller_bg.png'),
  facebook: require('../Images/facebook.png'),
  twitter: require('../Images/twitter.png'),
  insta: require('../Images/inst.png'),
  whatsapp: require('../Images/whatsapp.png'),
  mail: require('../Images/mail.png'),
  email: require('../Images/email.png'),
  notificationIconDark: require('../Images/notification_icon.png'),
  deleteIcon: require('../Images/delete_icon.png'),
  chevronAr: require('../Images/arrowAr.png'),
  image6: require('../Images/6.jpg'),
  image7: require('../Images/7.jpg'),
  imageb4: require('../Images/b4.jpg'),
  imageb3: require('../Images/b3.jpg'),
  imageb5: require('../Images/b5.jpg'), 
  imageb1: require('../Images/b1.jpg'), 
  imageb2: require('../Images/b2.jpg'), 
  image3: require('../Images/3.jpg'), 
  image2: require('../Images/2.jpg'), 
  image1: require('../Images/1.jpg'), 
  image4: require('../Images/4.jpg'), 
  image5: require('../Images/5.jpg'), 
  image8: require('../Images/8.jpg'), 
  image10: require('../Images/10.jpg'), 
  image13: require('../Images/13.jpg'), 
  image15: require('../Images/15.jpg'), 
  image18: require('../Images/18.jpg'), 
  image26: require('../Images/26.jpg'), 
// buttonBackground: require('../Images/button-bg.png'),
// api: require('../Images/Icons/icon-api-testing.png'),
// components: require('../Images/Icons/icon-components.png'),
// deviceInfo: require('../Images/Icons/icon-device-information.png'),
// faq: require('../Images/Icons/faq-icon.png'),
// home: require('../Images/Icons/icon-home.png'),
// theme: require('../Images/Icons/icon-theme.png'),
// usageExamples: require('../Images/Icons/icon-usage-examples.png'),
// chevronRight: require('../Images/Icons/chevron-right.png'),
// hamburger: require('../Images/Icons/hamburger.png'),
// backButton: require('../Images/Icons/back-button.png'),
// closeButton: require('../Images/Icons/close-button.png')
}

export default Images
